{% set name = "napari-turing" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-turing-{{ version }}.tar.gz
  sha256: d34413ca2fa27b7c4419f3fb7e1b9ba1f077d421ba7d744a1943caa41a3e20e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - napari_turing
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leoguignard/napari-turing
  summary: A plugin to run simmple simulations of Turing patterns
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
